# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Use a lightweight Node.js base image
FROM node:lts-alpine AS builder

WORKDIR /app

# Copy package manifest files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy source files
COPY tsconfig.json ./
COPY src ./src

# Build the project
RUN npm run build

# Second stage: production image
FROM node:lts-alpine AS runtime
WORKDIR /app

# Copy built artifacts and dependencies
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

# Ensure the entrypoint is executable
RUN chmod +x dist/index.js

ENTRYPOINT ["node", "dist/index.js"]
